// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table Stocks (Date:datetime, Open:real, High:real, Low:real, Close:real, AdjClose:real, Volume:string, Ticker:string) 
.create-or-alter table Stocks ingestion json mapping 'Stocks_Mapping'
```
[{"Properties":{"Path":"$['Date']"},"column":"Date","datatype":""},{"Properties":{"Path":"$['Open']"},"column":"Open","datatype":""},{"Properties":{"Path":"$['High']"},"column":"High","datatype":""},{"Properties":{"Path":"$['Low']"},"column":"Low","datatype":""},{"Properties":{"Path":"$['Close']"},"column":"Close","datatype":""},{"Properties":{"Path":"$['AdjClose']"},"column":"AdjClose","datatype":""},{"Properties":{"Path":"$['Volume']"},"column":"Volume","datatype":""},{"Properties":{"Path":"$['Ticker']"},"column":"Ticker","datatype":""}]
```
