CREATE TABLE [dbo].[FactInternetSales] (

	[ProductKey] bigint NULL, 
	[OrderDateKey] bigint NULL, 
	[DueDateKey] bigint NULL, 
	[ShipDateKey] bigint NULL, 
	[CustomerKey] bigint NULL, 
	[PromotionKey] bigint NULL, 
	[CurrencyKey] bigint NULL, 
	[SalesTerritoryKey] bigint NULL, 
	[SalesOrderNumber] varchar(8000) NULL, 
	[SalesOrderLineNumber] bigint NULL, 
	[RevisionNumber] bigint NULL, 
	[OrderQuantity] bigint NULL, 
	[UnitPrice] float NULL, 
	[ExtendedAmount] float NULL, 
	[UnitPriceDiscountPct] bigint NULL, 
	[DiscountAmount] bigint NULL, 
	[ProductStandardCost] float NULL, 
	[TotalProductCost] float NULL, 
	[SalesAmount] float NULL, 
	[TaxAmt] float NULL, 
	[Freight] float NULL, 
	[CarrierTrackingNumber] varchar(8000) NULL, 
	[CustomerPONumber] varchar(8000) NULL, 
	[OrderDate] date NULL, 
	[DueDate] date NULL, 
	[ShipDate] date NULL
);